Algoritmo "Orientação a Objetos"

tipo
cadastroCliente = registro
  nome : caractere
  rg : caractere
  idade : inteiro
fimregistro
Var

clienteUm : cadastroCliente


Inicio

Escreval("Digite seu nome: ")
leia(clienteUm.nome)

Escreval("Digite seu rg: ")
leia(clienteUm.rg)

Escreval("Digite sua idade: ")
leia(clienteUm.idade)

Escreval("Nome: ", clienteUm.nome, " - Rg: ", clienteUm.rg, " Idade: ", clienteUm.idade)



Fimalgoritmo